define(function(require, exports, module){ 
	var services = require('./services') ;

	services.factory('TableStatusServcie', function(){
	    return {
	        "tb183":{
	        	"showFlag":false,
	        },
	        "tb171":{
	        	"showFlag":false,
	        },
	        "tb172":{
	        	"showFlag":false,
	        },
	        "tb173Ticket":{
	        	"showFlag":false,
	        },
	        "tb173Tkt":{
	        	"showFlag":false,
	        },
	        "tb165":{
	        	"showFlag":false,
	        },
	        "tb186":{
	        	"showFlag":false,
	        },
	        "tb196":{
	        	"showFlag":false,
	        },
	        "tb198":{
	        	"showFlag":false,
	        },
	        "tb198UpGrade":{
	        	"showFlag":false,
	        },
	        "tb170":{
	        	"showFlag":true,
	        },
	        "tb178geo1":{
	        	"showFlag":false,
	        },
	        "tb178geo2":{
	        	"showFlag":false,
	        },
	        "tb178geo3":{
	        	"showFlag":false,
	        }
	    };
	}) ;


	services.factory('FormEditStatusServcie', function(){
	    return {
	        "firstMaintenanceDate":true,
	        "lastMaintenanceDate":true,
	        "description":true,
	        "fareBasis":true,
	        "availability":true,
	        "freeBaggageAllowancePieces":true,
	        "firstExcessOccurrence":true,
	        "lastExcessOccurrence":true,
	        "freeBaggageAllowanceWeight":true,
	        "freeBaggageAllowanceUnit":true,
	        "baggageTravelApplication":true,
	        "list196VO":true,
	        "noChargeNotAvailable":true,
	        "list170VO":true,
	        "list201VO":true,
	        "specSevFeeAndOrIndicator":true,
	        "specifiedServiceFeeMileage":true,
	        "specifiedServiceFeeApp":true,
	        "specServiceFeeColSub":true,
	        "specServiceFeeNetSell":true,
	        "indicatorComission":true,
	        "taxApplication":true,
	        "sequenceNumber":true,
	        "passengerTypeCode":true,
	        "minPassengerAge":true,
	        "maxPassengerAge":true,
	        "firstPassengerOccurrence":true,
	        "lastPassengerOccurrence":true,
	        "frequentFlyerStatus":true,
	        "mileageMinimum":true,
	        "mileageMaximum":true,
	        "customerIndexScoreMinimum":true,
	        "customerIndexScoreMaxmum":true,
	        "list172VO":true,
	        "list183VO":true,
	        "publicPrivateIndicator":true,
	        "geoSpecFromToWithin":true,
	        "geoSpecSectPortJourney":true,
	        "geoSpecTravelIndicator":true,
	        "geoSpecExceptionStopTime":true,
	        "geoSpecExceptionStopUnit":true,
	        "geoSpecStopConnDes":true,
	        "geoSpecLoc1Type":true,
	        "geoSpecLoc1":true,
	        "list178Loc1":true,
	        "geoSpecLoc2Type":true,
	        "geoSpecLoc2":true,
	        "geoSpecLoc3Type":true,
	        "geoSpecLoc3":true,
	        "list178Loc3":true,
	        "travelStartDate":true,
	        "travelEndDate":true,
	        "startTime":true,
	        "stopTime":true,
	        "timeApplication":true,
	        "dayOfWeek":true,
	        "equipment":true,
	        "list165VO":true,
	        "list186VO":true,
	        "cabin":true,
	        "list198VO":true,
	        "upgradeToCabin":true,
	        "list198UpgradeVO":true,
	        "advancedPurchasePeriod":true,
	        "advancedPurchaseUnit":true,
	        "tourCode":true,
	        "list173TicketVO":true,
	        "tariff":true,
	        "rule":true,
	        "list173TktVO":true,
	        "list171VO":true,
	        "advancedPurchaseTktIssue":true,
	        "indicatorReissueRefund":true,
	        "formOfRefund":true,
	        "indicatorInterline":true
	    };
	}) ;


	//整个页面的组件在serviceType为xxx时应该显示到页面上
	services.factory('FormStatusService', function(){
	    return {
	        "firstMaintenanceDate":{
	        	"typeList":['F','M','R','T','A','B','C','E','P'],
	        	"groupList":[],
	        	"nameList":['firstMaintenanceDate'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "lastMaintenanceDate":{
	        	"typeList":['F','M','R','T','A','B','C','E','P'],
	        	"groupList":[],
	        	"nameList":['lastMaintenanceDate'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "description":{
	        	"typeList":['F','M','R','T','B','E'],
	        	"groupList":[],
	        	"nameList":['description'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "fareBasis":{
	        	"typeList":['F','M','R','T','A','B','C','E','P'],
	        	"groupList":[],
	        	"nameList":['fareBasis'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "availability":{
	        	"typeList":['F','M','R','T','A','B','C','E','P'],
	        	"groupList":[],
	        	"nameList":['availability'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "freeBaggageAllowancePieces":{
	        	"typeList":['A'],
	        	"groupList":[],
	        	"nameList":['freeBaggageAllowancePieces'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "firstAndLastExcessOccurrence":{
	        	"typeList":['C','P'],
	        	"groupList":[],
	        	"nameList":['firstExcessOccurrence','lastExcessOccurrence'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "freeBaggageAllowanceWeight":{
	        	"typeList":['A','C','P'],
	        	"groupList":[],
	        	"nameList":['freeBaggageAllowanceWeight','freeBaggageAllowanceUnit'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
	        "baggageTravelApplication":{
	        	"typeList":['A','C','P'],
	        	"groupList":[],
	        	"nameList":['baggageTravelApplication'],
	        	"showFlag":true,
	        	"editFlag":true
	        },
			"list196VO":{
				"typeList":['A','C','P'],
				"groupList":[],
				"nameList":['list196VO'],
				"showFlag":true,
				"editFlag":true
			},
			"noChargeNotAvailable":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['noChargeNotAvailable'],
				"showFlag":true,
				"editFlag":true
			},
			"list170VOAndlist201VO":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['list170VO','list201VO'],
				"showFlag":true,
				"editFlag":true
			},
			"specSevFeeAndOrIndicator":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['specSevFeeAndOrIndicator'],
				"showFlag":true,
				"editFlag":true
			},
			"specifiedServiceFeeMileage":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['specifiedServiceFeeMileage'],
				"showFlag":true,
				"editFlag":true
			},
			"specifiedServiceFeeApp":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['specifiedServiceFeeApp'],
				"showFlag":true,
				"editFlag":true
			},
			"specServiceFeeColSub":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['specServiceFeeColSub'],
				"showFlag":true,
				"editFlag":true
			},
			"specServiceFeeNetSell":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['specServiceFeeNetSell'],
				"showFlag":true,
				"editFlag":true
			},
			"indicatorComission":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['indicatorComission'],
				"showFlag":true,
				"editFlag":true
			},
			"taxApplication":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['taxApplication'],
				"showFlag":true,
				"editFlag":true
			},
			"sequenceNumber":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['sequenceNumber'],
				"showFlag":true,
				"editFlag":true
			},
			"passengerTypeCode":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['passengerTypeCode'],
				"showFlag":true,
				"editFlag":true
			},
			"minAndMaxPassengerAge":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['minPassengerAge','maxPassengerAge'],
				"showFlag":true,
				"editFlag":true
			},
			"firstAndLastPassengerOccurrence":{
				"typeList":['F','M','R','T'],
				"groupList":[],
				"nameList":['firstPassengerOccurrence','lastPassengerOccurrence'],
				"showFlag":true,
				"editFlag":true
			},
			"frequentFlyerStatus":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['frequentFlyerStatus'],
				"showFlag":true,
				"editFlag":true
			},
			"mileageMinAndMaximum":{
				"typeList":['F','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['mileageMinimum','mileageMaximum'],
				"showFlag":true,
				"editFlag":true
			},
			"customerIndexScoreMinAndMaximum":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['customerIndexScoreMinimum','customerIndexScoreMaxmum'],
				"showFlag":true,
				"editFlag":true
			},
			"list172VO":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['list172VO'],
				"showFlag":true,
				"editFlag":true
			},
			"list183VO":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['list183VO'],
				"showFlag":true,
				"editFlag":true
			},
			"publicPrivateIndicator":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['publicPrivateIndicator'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecFromToWithin":{
				"typeList":['F','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecFromToWithin'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecSectPortJourney":{
				"typeList":['F','R','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecSectPortJourney'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecTravelIndicator":{
				"typeList":['F','R','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecTravelIndicator'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecExceptionStopTimeAndUnit":{
				"typeList":['F','R','A','C','P'],
				"groupList":[],
				"nameList":['geoSpecExceptionStopTime','geoSpecExceptionStopUnit'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecStopConnDes":{
				"typeList":['F','R','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecStopConnDes'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecLoc1AndType":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecLoc1Type','geoSpecLoc1'],
				"showFlag":true,
				"editFlag":true
			},
			"list178Loc1":{
				"typeList":['F','M','A','C','P','T'],
				"groupList":[],
				"nameList":['list178Loc1'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecLoc2AndType":{
				"typeList":['F','R','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecLoc2Type','geoSpecLoc2'],
				"showFlag":true,
				"editFlag":true
			},
			"list178Loc2":{
				"typeList":['F','M','A','C','P','T'],
				"groupList":[],
				"nameList":['list178Loc2'],
				"showFlag":true,
				"editFlag":true
			},
			"geoSpecLoc3AndType":{
				"typeList":['F','R','A','B','C','E','P'],
				"groupList":[],
				"nameList":['geoSpecLoc3Type','geoSpecLoc3'],
				"showFlag":true,
				"editFlag":true
			},
			"list178Loc3":{
				"typeList":['F','M','A','C','P','T'],
				"groupList":[],
				"nameList":['list178Loc3'],
				"showFlag":true,
				"editFlag":true
			},
			"travelStartDate":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['travelStartDate'],
				"showFlag":true,
				"editFlag":true
			},
			"travelEndDate":{
				"typeList":['F','M','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['travelEndDate'],
				"showFlag":true,
				"editFlag":true
			},
			"startTime":{
				"typeList":['F','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['startTime'],
				"showFlag":true,
				"editFlag":true
			},
			"stopTime":{
				"typeList":['F','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['stopTime'],
				"showFlag":true,
				"editFlag":true
			},
			"timeApplication":{
				"typeList":['hidden'],
				"groupList":[],
				"nameList":['timeApplication'],
				"showFlag":true,
				"editFlag":true
			},
			"dayOfWeek":{
				"typeList":['F','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['dayOfWeek'],
				"showFlag":true,
				"editFlag":true
			},
			"equipmentAndlist165":{
				"typeList":['F','A','B','C','E','P'],
				"groupList":[],
				"nameList":['equipment','list165VO'],
				"showFlag":true,
				"editFlag":true
			},
			"list186VO":{
				"typeList":['F','R','T','A','B','C','E','P'],
				"groupList":[],
				"nameList":['list186VO'],
				"showFlag":true,
				"editFlag":true
			},
			"cabin":{
				"typeList":['F','A','B','C','P'],
				"groupList":[],
				"nameList":['cabin'],
				"showFlag":true,
				"editFlag":true
			},
			"list198VO":{
				"typeList":['F','A','B','C','P'],
				"groupList":[],
				"nameList":['list198VO'],
				"showFlag":true,
				"editFlag":true
			},
			"upgradeToCabin":{
				"typeList":['F','M'],
				"groupList":['UP','BDUP'],
				"nameList":['upgradeToCabin'],
				"showFlag":true,
				"editFlag":true
			},
			"list198UpgradeVO":{
				"typeList":['F','M'],
				"groupList":['UP','BDUP','SA','BDSA'],
				"nameList":['list198UpgradeVO'],
				"showFlag":true,
				"editFlag":true
			},
			"advancedPurchasePeriodAndUnit":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['advancedPurchasePeriod','advancedPurchaseUnit'],
				"showFlag":true,
				"editFlag":true
			},
			"tourCode":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['tourCode'],
				"showFlag":true,
				"editFlag":true
			},
			"list173TicketVO":{
				"typeList":['F','M','R','T','A','B','C','P'],
				"groupList":[],
				"nameList":['list173TicketVO'],
				"showFlag":true,
				"editFlag":true
			},
			"tariff":{
				"typeList":['F','R','A','B','C','P'],
				"groupList":[],
				"nameList":['tariff'],
				"showFlag":true,
				"editFlag":true
			},
			"rule":{
				"typeList":['F','R','A','B','C','P'],
				"groupList":[],
				"nameList":['rule'],
				"showFlag":true,
				"editFlag":true
			},
			"list173TktVO":{
				"typeList":['F','R','A','B','C','P'],
				"groupList":[],
				"nameList":['list173TktVO'],
				"showFlag":true,
				"editFlag":true
			},
			"list171VO":{
				"typeList":['F','R','A','B','C','P'],
				"groupList":[],
				"nameList":['list171VO'],
				"showFlag":true,
				"editFlag":true
			},
			"advancedPurchaseTktIssue":{
				"typeList":['F','R','T','P'],
				"groupList":[],
				"nameList":['advancedPurchaseTktIssue'],
				"showFlag":true,
				"editFlag":true
			},
			"indicatorReissueRefund":{
				"typeList":['F','M','A','C','P','T'],
				"groupList":[],
				"nameList":['indicatorReissueRefund'],
				"showFlag":true,
				"editFlag":true
			},
			"formOfRefund":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['formOfRefund'],
				"showFlag":true,
				"editFlag":true
			},
			"indicatorInterline":{
				"typeList":['F','M','R','T','C','P'],
				"groupList":[],
				"nameList":['indicatorInterline'],
				"showFlag":true,
				"editFlag":true
			}
	    };
	}) ;

	

	

 }) ;
